export const assets = {
  forbes: '/assets/forbes.svg',
  health: '/assets/health.svg',
  noomWordmark: '/assets/noom-wordmark.svg',
  weightTrend: '/assets/weight-trend.svg',
  iconBody: '/assets/icon-body.svg',
  iconPills: '/assets/icon-pills.svg',
  iconCalendar: '/assets/icon-calendar.svg',
  iconStar: '/assets/icon-star.svg',
  dashedLine: '/assets/dashed-line.svg',
  divider: '/assets/divider.svg',
  dotBlue: '/assets/dot-blue.svg',
  dotGold: '/assets/dot-gold.svg',
  dotGreen: '/assets/dot-green.svg',
  check: '/assets/check.svg',
  checkFilled: '/assets/check-filled.svg',
  star: '/assets/star.svg',
  ratingDivider: '/assets/rating-divider.svg',
  badgeTag: '/assets/badge-tag.svg',
  badgeStar: '/assets/badge-star.svg',
  magicWand: '/assets/magic-wand.svg',
  caretDown: '/assets/caret-down.svg',
  iconArrow: '/assets/icon-arrow.svg',
  iconArrowLg: '/assets/icon-arrow-lg.svg',
  logoNoom: '/assets/logo-noom.png',
  logoRemedy: '/assets/logo-remedy.png',
  logoHers: '/assets/logo-hers.png',
  logoHims: '/assets/logo-hims.png',
  logoSprout: '/assets/logo-sprout.png',
  logoIvim: '/assets/logo-ivim.png',
  logoEden: '/assets/logo-eden.png',
} as const

export type AssetSrc = (typeof assets)[keyof typeof assets]
